name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt-get install -y curl git

    - name: Install Wasp CLI
      run: |
        curl -sSL https://get.wasp-lang.dev/installer.sh | sh
        echo 'export PATH="$HOME/.wasp/bin:$PATH"' >> $GITHUB_ENV

    - name: Set up SQLite In-Memory Database URL
      run: echo "DATABASE_URL=file:memory?mode=memory&cache=shared" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: wasp build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web-app  # Update this based on where Wasp outputs the built app