name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: goguma_db
          POSTGRES_USER: goguma_user
          POSTGRES_PASSWORD: goguma_password
        options: >-
          --health-cmd="pg_isready -U goguma_user" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt-get install -y curl git

    - name: Install Wasp CLI
      run: |
        curl -sSL https://get.wasp-lang.dev/installer.sh | sh
        echo 'export PATH="$HOME/.wasp/bin:$PATH"' >> $GITHUB_ENV

    - name: Set up PostgreSQL Environment Variable
      run: echo "DATABASE_URL=postgresql://goguma_user:goguma_password@localhost:5432/goguma_db" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run Prisma Migrate
      run: npx prisma migrate deploy

    - name: Build the project
      run: wasp build

    - name: Move build output to /docs
      run: mv ./build/web-app ./docs

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add docs
        git commit -m "Deploy build to GitHub Pages"
        git push origin main

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs